-- Seed global topic tags (user_id = null → visible to all users)
insert into public.tags (user_id, name) values
  (null, 'Array'),
  (null, 'Hash Table'),
  (null, 'Linked List'),
  (null, 'Math'),
  (null, 'Two Pointers'),
  (null, 'String'),
  (null, 'Binary Search'),
  (null, 'Divide and Conquer'),
  (null, 'Dynamic Programming'),
  (null, 'Backtracking'),
  (null, 'Stack'),
  (null, 'Heap (Priority Queue)'),
  (null, 'Graph'),
  (null, 'BFS'),
  (null, 'DFS'),
  (null, 'Union Find'),
  (null, 'Topological Sort'),
  (null, 'Sliding Window'),
  (null, 'Prefix Sum'),
  (null, 'Monotonic Stack'),
  (null, 'Trie'),
  (null, 'Tree'),
  (null, 'Binary Tree'),
  (null, 'Binary Search Tree'),
  (null, 'Segment Tree'),
  (null, 'Bit Manipulation'),
  (null, 'Greedy'),
  (null, 'Sorting'),
  (null, 'Design'),
  (null, 'Simulation')
on conflict do nothing;
